import assert from "node:assert/strict";
import { generateRing } from "../public/js/ring-generator.js";
import { validateAll } from "../public/js/brush-validation.js";
import { roundToGrid } from "../public/js/grid.js";
import { applySelection, ringVertexIds, selectByShape } from "../public/js/selection.js";
import { History } from "../public/js/history.js";
import { box, moveBrushes, moveVertices } from "../public/js/geometry-model.js";
import { parseVMF } from "../public/js/vmf-parser.js";
import { writeVMF } from "../public/js/vmf-writer.js";

const ring = generateRing({ radius: 256, width: 64, height: 128, segments: 8, grid: 16 });
assert.equal(validateAll(ring).length, 0, "generated ring must contain valid convex solids");
assert.equal(roundToGrid(1.1, 0.125), 1.125, "grid rounding must use the shared Hammer rule");
assert.equal(selectByShape([{ x: 0, y: 0 }, { x: 1, y: 1 }, { x: 2, y: 0 }], { x: 0, y: 0, r: 1 }, "circle").length, 1, "circle selection must use circular distance");
const inner = ringVertexIds(ring, "inner");
const outer = ringVertexIds(ring, "outer");
assert.equal(inner.length, 32);
assert.equal(outer.length, 32);
assert.equal(new Set(inner).size, inner.length);
assert.equal(applySelection(new Set(), inner.slice(0, 2), "replace").size, 2);
assert.equal(applySelection(new Set(inner), inner.slice(0, 2), "remove").size, 30);
const history = new History();
history.push({ value: 1 });
history.push({ value: 2 });
assert.deepEqual(history.undo(), { value: 1 });
assert.deepEqual(history.redo(), { value: 2 });
const selectionHistory = new History();
selectionHistory.push({ selection: [], brushSelection: [] });
selectionHistory.push({ selection: ["brush:v:0"], brushSelection: [] });
assert.deepEqual(selectionHistory.undo(), { selection: [], brushSelection: [] }, "undo must restore vertex selections");
assert.deepEqual(selectionHistory.redo(), { selection: ["brush:v:0"], brushSelection: [] }, "redo must restore vertex selections");
const imported = { id: "imported", vertices: [{ x: 0.25, y: 0, z: 0 }] };
moveVertices([imported], new Set(["imported:v:0"]), { x: 1, y: 0, z: 0 }, 1, false);
assert.equal(imported.vertices[0].x, 1.25, "drag snapping must preserve imported vertex offsets");
const object = { id: "object", vertices: [{ x: 0.25, y: 2, z: 3 }, { x: 4.25, y: 5, z: 6 }] };
moveBrushes([object], new Set(["object"]), { x: 8, y: -4, z: 0 }, 1, false);
assert.deepEqual(object.vertices, [{ x: 8.25, y: -2, z: 3 }, { x: 12.25, y: 1, z: 6 }], "object movement must translate every brush vertex while preserving imported offsets");
const grouped = [box(), box({ x: 128, y: -64, z: 0 }, { x: 256, y: 64, z: 128 })];
grouped.forEach(brush => { brush.groupId = "ring-group"; });
const groupedRoundTrip = parseVMF(writeVMF(grouped));
assert.equal(groupedRoundTrip.length, 2, "grouped brushes must survive VMF export and import");
assert.ok(groupedRoundTrip[0].groupId, "Hammer group ID must be imported");
assert.equal(groupedRoundTrip[0].groupId, groupedRoundTrip[1].groupId, "brushes in one Hammer group must retain a shared group ID");
console.log("milestone tests passed");
